# Generated by Django 3.1.3 on 2020-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201210_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='origional_bag',
            new_name='original_bag',
        ),
    ]
