# Generated by Django 3.1.3 on 2020-12-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0004_auto_20201210_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='User_Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
        ),
    ]
