# Generated by Django 3.1.3 on 2021-01-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210122_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
